services:
  - type: web
    name: realestateabroad-cms
    runtime: node
    plan: starter
    region: oregon
    branch: master
    buildCommand: rm -rf node_modules package-lock.json && npm cache clean --force && npm install && npm run build
    startCommand: npm start
    healthCheckPath: /admin
    envVars:
      - key: NODE_VERSION
        value: 20.19.4
      - key: NPM_CONFIG_ENGINE_STRICT
        value: true
      - key: FORCE_STRAPI_V4
        value: true
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        value: https://realestateabroad-cms.onrender.com
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_HOST
        value: dpg-d2jhc3be5dus739462a0-a
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        value: realestateabroad_cms
      - key: DATABASE_USERNAME
        value: realestateabroad_user
      - key: DATABASE_PASSWORD
        value: 1hLK0jhaD62gKvLpjc3YzUSLUTpf2rLy
      - key: DATABASE_SSL
        value: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true